from __future__ import annotations

"""生成轻量级实验报告。"""

from pathlib import Path


def generate_markdown_report(
    metrics: dict,
    report_path: str | Path,
    title: str = "Wake/Sleep Baseline Report",
) -> None:
    """根据指标生成 Markdown 报告。"""
    report = Path(report_path)
    report.parent.mkdir(parents=True, exist_ok=True)

    cm = metrics.get("confusion_matrix", [])
    content = f"""# {title}

## Metrics

- Accuracy: {metrics.get("accuracy", 0):.4f}
- Macro F1: {metrics.get("f1_macro", 0):.4f}
- Sleep F1: {metrics.get("f1_binary_sleep", 0):.4f}

## Confusion Matrix

Rows are true labels, columns are predicted labels.

```text
{cm}
```

## Notes

- This is a baseline report generated by the pure Python pipeline.
- DeepSeek-based result interpretation will be added in a later version.
"""
    report.write_text(content, encoding="utf-8")
